### ISSUE TITLE
200629-Quick-Media 中文二维码支持 - 一灰灰Blog

### ISSUE THREAD

**Issue by liuyueyi** [liuyueyi/hexblog#148]
https://blog.hhui.top/hexblog/2020/06/29/200629-Quick-Media-%E4%B8%AD%E6%96%87%E4%BA%8C%E7%BB%B4%E7%A0%81%E6%94%AF%E6%8C%81/ 

 Quick-Media 项目提供了一些列多媒体操作的开箱即用工具类，比如图片编辑合成，markdown/html/svg渲染，音频处理；当然还有本文重点说明的二维码生成解析 QrCode-Plugin支持丰富的酷炫二维码生成，大概十来天前有个小伙伴提了一个非常有意思的方向，能否将二维码中的黑白方块换成中文  趁着端午放假前夕的空闲时间，把这个集成在QrCode插件中，生成效果如下（从左往右，从上往

**Comment by lhllovezj** [comment]
您好，这个的jar包，能私发我一下吗？ 我引用不了

**Comment by lhllovezj** [comment]
现在问题是是依赖导不进来
